
# It will create `$AWS_S3_BUCKET.auto-deploy` s3 bucket if not exist and build
#the react app and Deploy it

name: Create s3,Build and deploy react app

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy react app
      uses: razzkumar/pr-automation-with-s3@v1.0.0
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}   # attach auto-deploy on name while creating s3 bucket
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ACTION: 'deploy'             # action must be deploy
